from fpdf import FPDF
import datetime

def generate_risk_assessment(trust_score, comp, valid, acc, consist):
    if trust_score >= 90:
        risk_level = "LOW RISK"
        verdict = "The dataset is structurally sound and safe for production analytics."
    elif trust_score >= 70:
        risk_level = "MODERATE RISK"
        verdict = "Significant noise or inconsistencies detected. Review before use."
    else:
        risk_level = "HIGH RISK"
        verdict = "Data is unreliable. Significant structural or integrity failures found."

    actions = []
    
    crit_cols = [c for c, m in comp.items() if m['status'] == 'Critical']
    invalid_cols = [c for c, m in valid.items() if m['status'] == 'Critical']
    
    if crit_cols:
        actions.append(f"High missingness in {', '.join(crit_cols)}.")
    if invalid_cols:
        actions.append(f"Type mismatches detected in {', '.join(invalid_cols)}.")
    
    # Check Outliers
    high_outliers = [c for c, m in acc.items() if m['status'] == 'Critical']
    if high_outliers:
        actions.append(f"Excessive outliers in {', '.join(high_outliers)} may bias analysis.")

    if any(i['status'] != 'Excellent' for i in consist if "rule" in i):
        actions.append("Logical pattern breaches found in Consistency report.")

    action_plan = " | ".join(actions) if actions else "No immediate corrective actions required."
    return risk_level, verdict, action_plan

def generate_pdf(trust_score, comp, dupe, valid, acc, consist, profile, dataset_name):
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15) 
    pdf.add_page()
    
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Data Trust Audit Report", 0, 1, "C")
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 8, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d')} | Dataset: {dataset_name}", 0, 1, "C")
    pdf.ln(5)
    pdf.set_font("Arial", "B", 26)
    pdf.cell(0, 20, f"Overall Trust Score: {trust_score}%", 0, 1, "C")
    pdf.ln(5)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "1. Dataset Identity", 0, 1)
    pdf.set_font("Arial", "", 10)
    intro_text = (f"Records: {profile['rows']} | Columns: {profile['cols']} | "
                  f"Numeric: {len(profile['numeric_cols'])} | Categorical: {len(profile['text_cols'])} | "
                  f"Size: {profile['file_size_kb']} KB")
    pdf.cell(0, 8, intro_text, 0, 1)

    risk_lvl, verdict, action_plan = generate_risk_assessment(trust_score, comp, valid, acc, consist)
    pdf.ln(5)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "2. Executive Risk Assessment", 0, 1)
    pdf.set_font("Arial", "B", 11)
    pdf.cell(30, 8, "STATUS:", 0, 0)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, risk_lvl, 0, 1)

    # pdf.multi_cell(0, 8, f"VERDICT: {verdict}", 0)

    pdf.set_font("Arial", "B", 11)
    pdf.write(8, "VERDICT: ") 
    pdf.set_font("Arial", "", 11)
    pdf.write(8, verdict) 
    pdf.ln(10)

    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 8, "Recommended Action Plan:", 0, 1)
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 6, action_plan, 0)

    # Completeness & Validity
    pdf.ln(10)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "3. Format & Completeness Audit", 0, 1)
    pdf.set_font("Arial", "B", 9)
    pdf.cell(50, 8, "Column", 1); pdf.cell(40, 8, "Type", 1); pdf.cell(30, 8, "Missing %", 1); pdf.cell(30, 8, "Valid %", 1); pdf.cell(35, 8, "Status", 1, 1)
    pdf.set_font("Arial", "", 9)
    for col in comp.keys():
        pdf.cell(50, 8, str(col)[:20], 1)
        pdf.cell(40, 8, valid[col]['inferred_type'], 1) # Display Smart Type
        pdf.cell(30, 8, f"{comp[col]['missing percentage']}%", 1)
        pdf.cell(30, 8, f"{valid[col]['valid_ratio']}", 1)
        pdf.cell(35, 8, comp[col]['status'], 1, 1)

    # Accuracy (Outliers)
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "4. Accuracy (Statistical Outliers)", 0, 1)
    pdf.set_font('Arial', 'B', 9)
    pdf.cell(60, 8, "Column", 1); pdf.cell(40, 8, "Method", 1); pdf.cell(40, 8, "Outliers", 1); pdf.cell(40, 8, "Status", 1, 1)
    pdf.set_font('Arial', '', 9)
    for col, m in acc.items():
        pdf.cell(60, 8, str(col)[:25], 1)
        pdf.cell(40, 8, m['method_used'], 1) 
        pdf.cell(40, 8, str(m['outlier_count']), 1)
        pdf.cell(40, 8, m['status'], 1, 1)

    # Consistency & Uniqueness 
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "5. Integrity & Uniqueness Summary", 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.multi_cell(0, 7, f"Duplicates found: {dupe['duplicate count']} ({dupe['duplicate percentage']}%). Status: {dupe['status']}", 0)
    for issue in consist:
        if issue['status'] != "Excellent":
            pdf.multi_cell(0, 7, f"LOGIC BREACH: {issue['rule']} | {issue['issue']}", 0)

    pdf.ln(10)
    pdf.set_font("Arial", "I", 8)
    pdf.cell(0, 10, "Report generated by Weighted Trust Scoring Engine", 0, 0, "C")

    return pdf.output(dest='S').encode('latin-1')